#!/bin/bash
# s2i-lib
# Copyright 2019 Marek Cermak <macermak@redhat.com>, Vaclav Pavlin <vpavlin@redhat.com>

set -euo pipefail

pushd $( [ ! -z $BASH ] && dirname "${BASH_SOURCE[0]}" || dirname "$0" ) > /dev/null

source "common.sh"
source "execution.sh"
source "requirements.sh"

popd > /dev/null
